apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce  # This PVC can be mounted by one pod at a time
  resources:
    requests:
      storage: 1Gi # Request 5 GB of storage