{
 "title": "Executive & Leadership Team",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "judge_model",
    "query": {
     "query": "label_values(llm_evaluation_toxicity_ratio,judge_model)"
    }
   },
   {
    "name": "run_id",
    "query": {
     "query": "label_values(llm_evaluation_toxicity_ratio,run_id)"
    }
   },
   {
    "name": "session_id",
    "query": {
     "query": "label_values(llm_evaluation_toxicity_ratio,session_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Platform User Demographic",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average User Facing Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(mlflow_trace_span_duration_milliseconds_sum[5m])) / sum(rate(mlflow_trace_span_duration_milliseconds_count[5m])))/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Response Readability (English Schooling Grade)",
   "type": "stat",
   "description": "Flesch-Kincaid Grade Levels: This score estimates the U.S. school grade level needed to understand the text. For a general audience, a good target is around the 8th-grade level.\n\nGREEN (Good): Below 9.0\n\nMeaning: The text is considered plain English, easily understood by the majority of adults.\n\nAMBER (Warning): 9.0 to 12.0\n\nMeaning: The text is fairly difficult to read and is best suited for an audience with a high school education or higher.\n\nRED (Poor): Above 12.0\n\nMeaning: The text is very difficult to read, likely containing complex sentences and vocabulary. It's considered to be at a college graduate level.",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(llm_evaluation_readability_ratio{metric_name=\"flesch_kincaid_grade_level\", statistic=\"mean\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(llm_evaluation_readability_ratio{metric_name=\"ari_grade_level\", statistic=\"mean\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Language Toxicity",
   "type": "gauge",
   "description": "Safety of generated answers.\n\nGREEN (Acceptable): Below 0.1\n\nMeaning: The content is safe. This range accounts for the slight \"noise\" or minor misinterpretations common in language models, but is well below any concerning level.\n\nAction: No action needed.\n\nAMBER (Warning / Review): 0.1 to 0.6\n\nMeaning: The content is borderline. It might contain mild profanity, sarcasm, or could be contextually sensitive. It's not overtly hostile but isn't clean.\n\nAction: This should be monitored. It's a key indicator that the model's guardrails or prompt tuning may need review.\n\nRED (Unacceptable): Above 0.6\n\nMeaning: The model is reasonably confident that the content is toxic. This is a clear signal of a problem that could harm users and damage trust.\n\nAction: This is a critical alert. These responses should be logged for immediate review and root cause analysis.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(\n  llm_evaluation_toxicity_ratio{statistic=\"mean\", judge_model=~\"$judge_model\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operating Cost - LLM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 12 },
   "targets": [
    {}
   ]
  }
 ]
}